### PR TITLE
update syllabus for coronavirus

### PR DESCRIPTION
**Pull request by wes-chen**
mondayid: 792792024

Changes:
added line in readme to reflect coronavirus >:(

### CODE REVIEW

**Comment by wes-chen** [comment]
(as bot)

this pr is attached to issue "asdfasdf" and has now been moved to Code Review.

**Review by bobbytatum27 — APPROVED** [review]
review

**Comment by wes-chen** [comment]
🆒

**Comment by wes-chen** [comment]
sorry this was just antoher demo

**Pull request closed without merging**
